apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: uselessmachines.introspect.actvirtual.com
spec:
  group: introspect.actvirtual.com
  version: v1alpha1
  names:
    kind: UselessMachine
    plural: uselessmachines
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            desiredState:
              enum:
              - "On"
              - "Off"
              type: string
